### ISSUE TITLE
Website via HTTPS

### ISSUE THREAD

**Issue by WyriHaximus** [reactphp/website#18]
We received a tweet yesterday about the inability to reach the website via HTTPS: https://twitter.com/_le_futuriste/status/898835476827828224

We can handle this in a few different ways:
- Do nothing and wait for @Github to support it
- Set up an AWS CloudFront distribution
- Set up CloudFlare

The latter is by far my favourite but I don't mind setting up the CloudFront distribution and paying for it 😄 .

**Comment by WyriHaximus** [comment]
@clue @jsor @cboden ^

**Comment by khanhicetea** [comment]
One more option is using free [netlify](https://www.netlify.com/) with LetsEncrypt SSL and Continuous Deployment

**Comment by jsor** [comment]
I think we should use CloudFare, it's easy to setup and free.

@khanhicetea We're already automatically deploying to the reactphp.github.io repo via Travis CI: https://travis-ci.org/reactphp/website

**Comment by cboden** [comment]
Sounds good. If that's the direction everyone agrees to go, let me know and I'll update the DNS records.

**Comment by clue** [comment]
I know we've discussed this in the past and I agree it's about time we should make this happen :+1: 

Given the type of content that's hosted on the site currently, I'd also suggest going with cloudflare, also because it's mostly zero maintenance :+1:

**Comment by WyriHaximus** [comment]
Seems we're all in agreement :+1: , @cboden can you update the DNS records? :tada:

**Comment by WyriHaximus** [comment]
Closing this as the website is now available through HTTPS: https://reactphp.org
