### ISSUE TITLE
Twig Extension undefined index notice

### ISSUE THREAD

**Issue by mattsches** [reactphp/website#40]
The ReactPHP website displays a PHP notice with its [stack trace](https://pastebin.com/XcGJwG3A) in the `activity` box on the lower right (see attached screenshot).

This happens because the `$participation` array does not contain the index `all`. Might have sth. to do with connectivity issues to Travis, or maybe they changed something on their side? 

![auswahl_029](https://user-images.githubusercontent.com/68414/44209693-841b8e00-a164-11e8-9ddb-4229f08d5ac1.png)

**Comment by WyriHaximus** [comment]
> We should probably fail the build in this case.

:+1: on failing the build in that case.

**Comment by jsor** [comment]
See #41
