### ISSUE TITLE
Website build does not include latest Datagram v1.9.0

### ISSUE THREAD

**Issue by clue** [reactphp/website#66]
For some reason, the website build process detects reactphp/datagram v1.8.0 as the latest version and and does not include the latest release: https://github.com/reactphp/datagram/releases/tag/v1.9.0

I've manually executed the build again, but the problem persists. See also last build output: https://github.com/reactphp/website/actions/runs/4151388784/jobs/7181669476#step:8:120

Only stumbled upon this today and haven't analyzed this in-depth yet, any help would be appreciated.

**Comment by SimonFrings** [comment]
@clue I just checked the ReactPHP website and it seems that the latest version of reactphp/datagram shows the `v1.9.0`. So it seems to me that this issue resolved itself in the meantime, so I'll go ahead and close this ticket.
